export const NoteCategories: string[] = [
  "Lecture Summary",
  "Handwritten Notes",
  "Important Questions",
  "Formula Sheet",
  "Previous Year Papers",
  "Solved Examples",
  "Assignments",
  "Computer Programs",
  "MS Office",
  "Presentations",
  "Project Reports",
  "Research Papers",
  "Thesis",
  "Case Studies",
  "E-books",
  "Mind Maps",
  "Diagrams & Charts",
  "Practice Worksheets",
  "Quick Revision Notes",
  "Conceptual Notes",
  "Lab Manuals / Practicals",
  "Study Planners / Schedules",
  "Syllabus & Blueprints",
  "Others"
];
